// Code generated by go-github-cli/generator; DO NOT EDIT.

package services

type CLI struct {
	Activity            ActivityCmd            `cmd:""`
	Apps                AppsCmd                `cmd:""`
	Checks              ChecksCmd              `cmd:""`
	CodesOfConduct      CodesOfConductCmd      `cmd:""`
	Emojis              EmojisCmd              `cmd:""`
	Gists               GistsCmd               `cmd:""`
	Git                 GitCmd                 `cmd:""`
	Gitignore           GitignoreCmd           `cmd:""`
	Issues              IssuesCmd              `cmd:""`
	Licenses            LicensesCmd            `cmd:""`
	Markdown            MarkdownCmd            `cmd:""`
	Meta                MetaCmd                `cmd:""`
	Migrations          MigrationsCmd          `cmd:""`
	OauthAuthorizations OauthAuthorizationsCmd `cmd:""`
	Orgs                OrgsCmd                `cmd:""`
	Projects            ProjectsCmd            `cmd:""`
	Pulls               PullsCmd               `cmd:""`
	RateLimit           RateLimitCmd           `cmd:""`
	Reactions           ReactionsCmd           `cmd:""`
	Repos               ReposCmd               `cmd:""`
	Scim                ScimCmd                `cmd:""`
	Search              SearchCmd              `cmd:""`
	Teams               TeamsCmd               `cmd:""`
	Users               UsersCmd               `cmd:""`
}
