// Code generated by octo-cli/generator; DO NOT EDIT.

package services

type EmojisCmd struct {
	Get EmojisGetCmd `cmd:"" help:"Get"`
}

type EmojisGetCmd struct {
	baseCmd
}

func (c *EmojisGetCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/emojis"
	return c.doRequest("GET")
}
