// Code generated by go-github-cli/generator; DO NOT EDIT.

package services

type LicensesCmd struct {
	List       LicensesListCmd       `cmd:"" help:"List all licenses"`
	Get        LicensesGetCmd        `cmd:"" help:"Get an individual license"`
	GetForRepo LicensesGetForRepoCmd `cmd:"" help:"Get the contents of a repository's license"`
}

type LicensesListCmd struct {
	baseCmd
}

func (c *LicensesListCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/licenses"
	return c.doRequest("GET")
}

type LicensesGetCmd struct {
	baseCmd
	License string `required:"" name:"license"`
}

func (c *LicensesGetCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/licenses/:license"
	c.updateURLPath("license", c.License)
	return c.doRequest("GET")
}

type LicensesGetForRepoCmd struct {
	baseCmd
	Owner string `required:"" name:"owner"`
	Repo  string `required:"" name:"repo"`
}

func (c *LicensesGetForRepoCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/repos/:owner/:repo/license"
	c.updateURLPath("owner", c.Owner)
	c.updateURLPath("repo", c.Repo)
	return c.doRequest("GET")
}
