// Code generated by go-github-cli/generator; DO NOT EDIT

package services

type MetaCmd struct {
	Get MetaGetCmd `cmd:"" help:"Get"`
}

type MetaGetCmd struct {
	baseCmd
}

func (c *MetaGetCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/meta"
	return c.doRequest("GET")
}
