// Code generated by octo-cli/generator; DO NOT EDIT.

package services

import "github.com/octo-cli/octo-cli/internal"

type ProjectsCmd struct {
	ListForRepo               ProjectsListForRepoCmd               `cmd:"" help:"List repository projects"`
	ListForOrg                ProjectsListForOrgCmd                `cmd:"" help:"List organization projects"`
	Get                       ProjectsGetCmd                       `cmd:"" help:"Get a project"`
	CreateForRepo             ProjectsCreateForRepoCmd             `cmd:"" help:"Create a repository project"`
	CreateForOrg              ProjectsCreateForOrgCmd              `cmd:"" help:"Create an organization project"`
	Update                    ProjectsUpdateCmd                    `cmd:"" help:"Update a project"`
	Delete                    ProjectsDeleteCmd                    `cmd:"" help:"Delete a project"`
	ListCards                 ProjectsListCardsCmd                 `cmd:"" help:"List project cards"`
	GetCard                   ProjectsGetCardCmd                   `cmd:"" help:"Get a project card"`
	CreateCard                ProjectsCreateCardCmd                `cmd:"" help:"Create a project card"`
	UpdateCard                ProjectsUpdateCardCmd                `cmd:"" help:"Update a project card"`
	DeleteCard                ProjectsDeleteCardCmd                `cmd:"" help:"Delete a project card"`
	MoveCard                  ProjectsMoveCardCmd                  `cmd:"" help:"Move a project card"`
	ListCollaborators         ProjectsListCollaboratorsCmd         `cmd:"" help:"List collaborators"`
	ReviewUserPermissionLevel ProjectsReviewUserPermissionLevelCmd `cmd:"" help:"Review a user's permission level"`
	AddCollaborator           ProjectsAddCollaboratorCmd           `cmd:"" help:"Add user as a collaborator"`
	RemoveCollaborator        ProjectsRemoveCollaboratorCmd        `cmd:"" help:"Remove user as a collaborator"`
	ListColumns               ProjectsListColumnsCmd               `cmd:"" help:"List project columns"`
	GetColumn                 ProjectsGetColumnCmd                 `cmd:"" help:"Get a project column"`
	CreateColumn              ProjectsCreateColumnCmd              `cmd:"" help:"Create a project column"`
	UpdateColumn              ProjectsUpdateColumnCmd              `cmd:"" help:"Update a project column"`
	DeleteColumn              ProjectsDeleteColumnCmd              `cmd:"" help:"Delete a project column"`
	MoveColumn                ProjectsMoveColumnCmd                `cmd:"" help:"Move a project column"`
}

type ProjectsListForRepoCmd struct {
	internal.BaseCmd
	Inertia bool   "name:\"inertia-preview\" required:\"\" help:\"The Projects API is currently available for developers to preview. During the preview period, the API may change without advance notice. Please see the [blog post](/changes/2016-10-27-changes-to-projects-api) for full details. To access the API during the preview period, you must provide a custom [media type](/v3/media) in the `Accept` header:\n\n```\n  application/vnd.github.inertia-preview+json\n\n```\""
	Owner   string `required:"" name:"owner"`
	Repo    string `required:"" name:"repo"`
	State   string "name:\"state\" help:\"Indicates the state of the projects to return. Can be either `open`, `closed`, or `all`.\""
	PerPage int64  `name:"per_page" help:"Results per page (max 100)"`
	Page    int64  `name:"page" help:"Page number of the results to fetch."`
}

func (c *ProjectsListForRepoCmd) Run(isValueSetMap map[string]bool) error {
	c.SetIsValueSetMap(isValueSetMap)
	c.SetURLPath("/repos/:owner/:repo/projects")
	c.UpdatePreview("inertia", c.Inertia)
	c.UpdateURLPath("owner", c.Owner)
	c.UpdateURLPath("repo", c.Repo)
	c.UpdateURLQuery("state", c.State)
	c.UpdateURLQuery("per_page", c.PerPage)
	c.UpdateURLQuery("page", c.Page)
	return c.DoRequest("GET")
}

type ProjectsListForOrgCmd struct {
	internal.BaseCmd
	Inertia bool   "name:\"inertia-preview\" required:\"\" help:\"The Projects API is currently available for developers to preview. During the preview period, the API may change without advance notice. Please see the [blog post](/changes/2016-10-27-changes-to-projects-api) for full details. To access the API during the preview period, you must provide a custom [media type](/v3/media) in the `Accept` header:\n\n```\n  application/vnd.github.inertia-preview+json\n\n```\""
	Org     string `required:"" name:"org"`
	State   string "name:\"state\" help:\"Indicates the state of the projects to return. Can be either `open`, `closed`, or `all`.\""
	PerPage int64  `name:"per_page" help:"Results per page (max 100)"`
	Page    int64  `name:"page" help:"Page number of the results to fetch."`
}

func (c *ProjectsListForOrgCmd) Run(isValueSetMap map[string]bool) error {
	c.SetIsValueSetMap(isValueSetMap)
	c.SetURLPath("/orgs/:org/projects")
	c.UpdatePreview("inertia", c.Inertia)
	c.UpdateURLPath("org", c.Org)
	c.UpdateURLQuery("state", c.State)
	c.UpdateURLQuery("per_page", c.PerPage)
	c.UpdateURLQuery("page", c.Page)
	return c.DoRequest("GET")
}

type ProjectsGetCmd struct {
	internal.BaseCmd
	Inertia   bool  "name:\"inertia-preview\" required:\"\" help:\"The Projects API is currently available for developers to preview. During the preview period, the API may change without advance notice. Please see the [blog post](/changes/2016-10-27-changes-to-projects-api) for full details. To access the API during the preview period, you must provide a custom [media type](/v3/media) in the `Accept` header:\n\n```\n  application/vnd.github.inertia-preview+json\n\n```\""
	ProjectId int64 `required:"" name:"project_id"`
	PerPage   int64 `name:"per_page" help:"Results per page (max 100)"`
	Page      int64 `name:"page" help:"Page number of the results to fetch."`
}

func (c *ProjectsGetCmd) Run(isValueSetMap map[string]bool) error {
	c.SetIsValueSetMap(isValueSetMap)
	c.SetURLPath("/projects/:project_id")
	c.UpdatePreview("inertia", c.Inertia)
	c.UpdateURLPath("project_id", c.ProjectId)
	c.UpdateURLQuery("per_page", c.PerPage)
	c.UpdateURLQuery("page", c.Page)
	return c.DoRequest("GET")
}

type ProjectsCreateForRepoCmd struct {
	internal.BaseCmd
	Inertia bool   "name:\"inertia-preview\" required:\"\" help:\"The Projects API is currently available for developers to preview. During the preview period, the API may change without advance notice. Please see the [blog post](/changes/2016-10-27-changes-to-projects-api) for full details. To access the API during the preview period, you must provide a custom [media type](/v3/media) in the `Accept` header:\n\n```\n  application/vnd.github.inertia-preview+json\n\n```\""
	Owner   string `required:"" name:"owner"`
	Repo    string `required:"" name:"repo"`
	Name    string `required:"" name:"name" help:"The name of the project."`
	Body    string `name:"body" help:"The body of the project."`
	PerPage int64  `name:"per_page" help:"Results per page (max 100)"`
	Page    int64  `name:"page" help:"Page number of the results to fetch."`
}

func (c *ProjectsCreateForRepoCmd) Run(isValueSetMap map[string]bool) error {
	c.SetIsValueSetMap(isValueSetMap)
	c.SetURLPath("/repos/:owner/:repo/projects")
	c.UpdatePreview("inertia", c.Inertia)
	c.UpdateURLPath("owner", c.Owner)
	c.UpdateURLPath("repo", c.Repo)
	c.UpdateBody("name", c.Name)
	c.UpdateBody("body", c.Body)
	c.UpdateURLQuery("per_page", c.PerPage)
	c.UpdateURLQuery("page", c.Page)
	return c.DoRequest("POST")
}

type ProjectsCreateForOrgCmd struct {
	internal.BaseCmd
	Inertia bool   "name:\"inertia-preview\" required:\"\" help:\"The Projects API is currently available for developers to preview. During the preview period, the API may change without advance notice. Please see the [blog post](/changes/2016-10-27-changes-to-projects-api) for full details. To access the API during the preview period, you must provide a custom [media type](/v3/media) in the `Accept` header:\n\n```\n  application/vnd.github.inertia-preview+json\n\n```\""
	Org     string `required:"" name:"org"`
	Name    string `required:"" name:"name" help:"The name of the project."`
	Body    string `name:"body" help:"The body of the project."`
	PerPage int64  `name:"per_page" help:"Results per page (max 100)"`
	Page    int64  `name:"page" help:"Page number of the results to fetch."`
}

func (c *ProjectsCreateForOrgCmd) Run(isValueSetMap map[string]bool) error {
	c.SetIsValueSetMap(isValueSetMap)
	c.SetURLPath("/orgs/:org/projects")
	c.UpdatePreview("inertia", c.Inertia)
	c.UpdateURLPath("org", c.Org)
	c.UpdateBody("name", c.Name)
	c.UpdateBody("body", c.Body)
	c.UpdateURLQuery("per_page", c.PerPage)
	c.UpdateURLQuery("page", c.Page)
	return c.DoRequest("POST")
}

type ProjectsUpdateCmd struct {
	internal.BaseCmd
	Inertia                bool   "name:\"inertia-preview\" required:\"\" help:\"The Projects API is currently available for developers to preview. During the preview period, the API may change without advance notice. Please see the [blog post](/changes/2016-10-27-changes-to-projects-api) for full details. To access the API during the preview period, you must provide a custom [media type](/v3/media) in the `Accept` header:\n\n```\n  application/vnd.github.inertia-preview+json\n\n```\""
	ProjectId              int64  `required:"" name:"project_id"`
	Name                   string `name:"name" help:"The name of the project."`
	Body                   string `name:"body" help:"The body of the project."`
	State                  string "name:\"state\" help:\"State of the project. Either `open` or `closed`.\""
	OrganizationPermission string "name:\"organization_permission\" help:\"The permission level that all members of the project's organization will have on this project. If an organization member belongs to a team with a higher level of access or is a collaborator with a higher level of access, their permission level is not lowered by `organization_permission`. Updating a project's organization permission requires `admin` access to the project. Setting the organization permission is only available for organization projects.\""
	Public                 bool   "name:\"public\" help:\"Sets visibility of the project within the organization. Updating a project's visibility requires `admin` access to the project. Setting visibility is only available for organization projects. Can be one of:  \n\\* `true` - Anyone that can view the organization can see the project.  \n\\* `false` - The project must be an organization project to set project visibility.\""
	PerPage                int64  `name:"per_page" help:"Results per page (max 100)"`
	Page                   int64  `name:"page" help:"Page number of the results to fetch."`
}

func (c *ProjectsUpdateCmd) Run(isValueSetMap map[string]bool) error {
	c.SetIsValueSetMap(isValueSetMap)
	c.SetURLPath("/projects/:project_id")
	c.UpdatePreview("inertia", c.Inertia)
	c.UpdateURLPath("project_id", c.ProjectId)
	c.UpdateBody("name", c.Name)
	c.UpdateBody("body", c.Body)
	c.UpdateBody("state", c.State)
	c.UpdateBody("organization_permission", c.OrganizationPermission)
	c.UpdateBody("public", c.Public)
	c.UpdateURLQuery("per_page", c.PerPage)
	c.UpdateURLQuery("page", c.Page)
	return c.DoRequest("PATCH")
}

type ProjectsDeleteCmd struct {
	internal.BaseCmd
	Inertia   bool  "name:\"inertia-preview\" required:\"\" help:\"The Projects API is currently available for developers to preview. During the preview period, the API may change without advance notice. Please see the [blog post](/changes/2016-10-27-changes-to-projects-api) for full details. To access the API during the preview period, you must provide a custom [media type](/v3/media) in the `Accept` header:\n\n```\n  application/vnd.github.inertia-preview+json\n\n```\""
	ProjectId int64 `required:"" name:"project_id"`
}

func (c *ProjectsDeleteCmd) Run(isValueSetMap map[string]bool) error {
	c.SetIsValueSetMap(isValueSetMap)
	c.SetURLPath("/projects/:project_id")
	c.UpdatePreview("inertia", c.Inertia)
	c.UpdateURLPath("project_id", c.ProjectId)
	return c.DoRequest("DELETE")
}

type ProjectsListCardsCmd struct {
	internal.BaseCmd
	Inertia       bool   "name:\"inertia-preview\" required:\"\" help:\"The Projects API is currently available for developers to preview. During the preview period, the API may change without advance notice. Please see the [blog post](/changes/2016-10-27-changes-to-projects-api) for full details. To access the API during the preview period, you must provide a custom [media type](/v3/media) in the `Accept` header:\n\n```\n  application/vnd.github.inertia-preview+json\n\n```\""
	ColumnId      int64  `required:"" name:"column_id"`
	ArchivedState string "name:\"archived_state\" help:\"Filters the project cards that are returned by the card's state. Can be one of `all`,`archived`, or `not_archived`.\""
	PerPage       int64  `name:"per_page" help:"Results per page (max 100)"`
	Page          int64  `name:"page" help:"Page number of the results to fetch."`
}

func (c *ProjectsListCardsCmd) Run(isValueSetMap map[string]bool) error {
	c.SetIsValueSetMap(isValueSetMap)
	c.SetURLPath("/projects/columns/:column_id/cards")
	c.UpdatePreview("inertia", c.Inertia)
	c.UpdateURLPath("column_id", c.ColumnId)
	c.UpdateURLQuery("archived_state", c.ArchivedState)
	c.UpdateURLQuery("per_page", c.PerPage)
	c.UpdateURLQuery("page", c.Page)
	return c.DoRequest("GET")
}

type ProjectsGetCardCmd struct {
	internal.BaseCmd
	Inertia bool  "name:\"inertia-preview\" required:\"\" help:\"The Projects API is currently available for developers to preview. During the preview period, the API may change without advance notice. Please see the [blog post](/changes/2016-10-27-changes-to-projects-api) for full details. To access the API during the preview period, you must provide a custom [media type](/v3/media) in the `Accept` header:\n\n```\n  application/vnd.github.inertia-preview+json\n\n```\""
	CardId  int64 `required:"" name:"card_id"`
}

func (c *ProjectsGetCardCmd) Run(isValueSetMap map[string]bool) error {
	c.SetIsValueSetMap(isValueSetMap)
	c.SetURLPath("/projects/columns/cards/:card_id")
	c.UpdatePreview("inertia", c.Inertia)
	c.UpdateURLPath("card_id", c.CardId)
	return c.DoRequest("GET")
}

type ProjectsCreateCardCmd struct {
	internal.BaseCmd
	Inertia     bool   "name:\"inertia-preview\" required:\"\" help:\"The Projects API is currently available for developers to preview. During the preview period, the API may change without advance notice. Please see the [blog post](/changes/2016-10-27-changes-to-projects-api) for full details. To access the API during the preview period, you must provide a custom [media type](/v3/media) in the `Accept` header:\n\n```\n  application/vnd.github.inertia-preview+json\n\n```\""
	ColumnId    int64  `required:"" name:"column_id"`
	Note        string "name:\"note\" help:\"The card's note content. Only valid for cards without another type of content, so you must omit when\u00a0specifying `content_id`\u00a0and\u00a0`content_type`.\""
	ContentId   int64  "name:\"content_id\" help:\"The issue or pull request id you want to associate with this card. You can use the [List issues for a repository](https://developer.github.com/v3/issues/#list-issues-for-a-repository) and [List pull requests](https://developer.github.com/v3/pulls/#list-pull-requests) endpoints to find this id.  \n**Note:** Depending on whether you use the issue id or pull request id, you will need to specify `Issue` or `PullRequest` as the `content_type`.\""
	ContentType string "name:\"content_type\" help:\"**Required if you provide\u00a0`content_id`**. The type of content you want to associate with this card. Use `Issue` when `content_id` is an issue id and use `PullRequest` when `content_id` is a pull request id.\""
}

func (c *ProjectsCreateCardCmd) Run(isValueSetMap map[string]bool) error {
	c.SetIsValueSetMap(isValueSetMap)
	c.SetURLPath("/projects/columns/:column_id/cards")
	c.UpdatePreview("inertia", c.Inertia)
	c.UpdateURLPath("column_id", c.ColumnId)
	c.UpdateBody("note", c.Note)
	c.UpdateBody("content_id", c.ContentId)
	c.UpdateBody("content_type", c.ContentType)
	return c.DoRequest("POST")
}

type ProjectsUpdateCardCmd struct {
	internal.BaseCmd
	Inertia  bool   "name:\"inertia-preview\" required:\"\" help:\"The Projects API is currently available for developers to preview. During the preview period, the API may change without advance notice. Please see the [blog post](/changes/2016-10-27-changes-to-projects-api) for full details. To access the API during the preview period, you must provide a custom [media type](/v3/media) in the `Accept` header:\n\n```\n  application/vnd.github.inertia-preview+json\n\n```\""
	CardId   int64  `required:"" name:"card_id"`
	Note     string "name:\"note\" help:\"The card's note content. Only valid for cards without another type of content, so this cannot be specified if the card already has a `content_id` and `content_type`.\""
	Archived bool   "name:\"archived\" help:\"Use `true` to archive a project card. Specify `false` if you need to restore a previously archived project card.\""
}

func (c *ProjectsUpdateCardCmd) Run(isValueSetMap map[string]bool) error {
	c.SetIsValueSetMap(isValueSetMap)
	c.SetURLPath("/projects/columns/cards/:card_id")
	c.UpdatePreview("inertia", c.Inertia)
	c.UpdateURLPath("card_id", c.CardId)
	c.UpdateBody("note", c.Note)
	c.UpdateBody("archived", c.Archived)
	return c.DoRequest("PATCH")
}

type ProjectsDeleteCardCmd struct {
	internal.BaseCmd
	Inertia bool  "name:\"inertia-preview\" required:\"\" help:\"The Projects API is currently available for developers to preview. During the preview period, the API may change without advance notice. Please see the [blog post](/changes/2016-10-27-changes-to-projects-api) for full details. To access the API during the preview period, you must provide a custom [media type](/v3/media) in the `Accept` header:\n\n```\n  application/vnd.github.inertia-preview+json\n\n```\""
	CardId  int64 `required:"" name:"card_id"`
}

func (c *ProjectsDeleteCardCmd) Run(isValueSetMap map[string]bool) error {
	c.SetIsValueSetMap(isValueSetMap)
	c.SetURLPath("/projects/columns/cards/:card_id")
	c.UpdatePreview("inertia", c.Inertia)
	c.UpdateURLPath("card_id", c.CardId)
	return c.DoRequest("DELETE")
}

type ProjectsMoveCardCmd struct {
	internal.BaseCmd
	Inertia  bool   "name:\"inertia-preview\" required:\"\" help:\"The Projects API is currently available for developers to preview. During the preview period, the API may change without advance notice. Please see the [blog post](/changes/2016-10-27-changes-to-projects-api) for full details. To access the API during the preview period, you must provide a custom [media type](/v3/media) in the `Accept` header:\n\n```\n  application/vnd.github.inertia-preview+json\n\n```\""
	CardId   int64  `required:"" name:"card_id"`
	Position string "required:\"\" name:\"position\" help:\"Can be one of `top`, `bottom`, or `after:<card_id>`, where `<card_id>` is the `id` value of a card in the same column, or in the new column specified by `column_id`.\""
	ColumnId int64  "name:\"column_id\" help:\"The `id` value of a column in the same project.\""
}

func (c *ProjectsMoveCardCmd) Run(isValueSetMap map[string]bool) error {
	c.SetIsValueSetMap(isValueSetMap)
	c.SetURLPath("/projects/columns/cards/:card_id/moves")
	c.UpdatePreview("inertia", c.Inertia)
	c.UpdateURLPath("card_id", c.CardId)
	c.UpdateBody("position", c.Position)
	c.UpdateBody("column_id", c.ColumnId)
	return c.DoRequest("POST")
}

type ProjectsListCollaboratorsCmd struct {
	internal.BaseCmd
	Inertia     bool   "name:\"inertia-preview\" required:\"\" help:\"The Projects API is currently available for developers to preview. During the preview period, the API may change without advance notice. Please see the [blog post](/changes/2016-10-27-changes-to-projects-api) for full details. To access the API during the preview period, you must provide a custom [media type](/v3/media) in the `Accept` header:\n\n```\n  application/vnd.github.inertia-preview+json\n\n```\""
	ProjectId   int64  `required:"" name:"project_id"`
	Affiliation string "name:\"affiliation\" help:\"Filters the collaborators by their affiliation. Can be one of:  \n\\* `outside`: Outside collaborators of a project that are not a member of the project's organization.  \n\\* `direct`: Collaborators with permissions to a project, regardless of organization membership status.  \n\\* `all`: All collaborators the authenticated user can see.\""
	PerPage     int64  `name:"per_page" help:"Results per page (max 100)"`
	Page        int64  `name:"page" help:"Page number of the results to fetch."`
}

func (c *ProjectsListCollaboratorsCmd) Run(isValueSetMap map[string]bool) error {
	c.SetIsValueSetMap(isValueSetMap)
	c.SetURLPath("/projects/:project_id/collaborators")
	c.UpdatePreview("inertia", c.Inertia)
	c.UpdateURLPath("project_id", c.ProjectId)
	c.UpdateURLQuery("affiliation", c.Affiliation)
	c.UpdateURLQuery("per_page", c.PerPage)
	c.UpdateURLQuery("page", c.Page)
	return c.DoRequest("GET")
}

type ProjectsReviewUserPermissionLevelCmd struct {
	internal.BaseCmd
	Inertia   bool   "name:\"inertia-preview\" required:\"\" help:\"The Projects API is currently available for developers to preview. During the preview period, the API may change without advance notice. Please see the [blog post](/changes/2016-10-27-changes-to-projects-api) for full details. To access the API during the preview period, you must provide a custom [media type](/v3/media) in the `Accept` header:\n\n```\n  application/vnd.github.inertia-preview+json\n\n```\""
	ProjectId int64  `required:"" name:"project_id"`
	Username  string `required:"" name:"username"`
}

func (c *ProjectsReviewUserPermissionLevelCmd) Run(isValueSetMap map[string]bool) error {
	c.SetIsValueSetMap(isValueSetMap)
	c.SetURLPath("/projects/:project_id/collaborators/:username/permission")
	c.UpdatePreview("inertia", c.Inertia)
	c.UpdateURLPath("project_id", c.ProjectId)
	c.UpdateURLPath("username", c.Username)
	return c.DoRequest("GET")
}

type ProjectsAddCollaboratorCmd struct {
	internal.BaseCmd
	Inertia    bool   "name:\"inertia-preview\" required:\"\" help:\"The Projects API is currently available for developers to preview. During the preview period, the API may change without advance notice. Please see the [blog post](/changes/2016-10-27-changes-to-projects-api) for full details. To access the API during the preview period, you must provide a custom [media type](/v3/media) in the `Accept` header:\n\n```\n  application/vnd.github.inertia-preview+json\n\n```\""
	ProjectId  int64  `required:"" name:"project_id"`
	Username   string `required:"" name:"username"`
	Permission string "name:\"permission\" help:\"The permission to grant the collaborator. Note that, if you choose not to pass any parameters, you'll need to set `Content-Length` to zero when calling out to this endpoint. For more information, see '[HTTP verbs](https://developer.github.com/v3/#http-verbs).' Can be one of:  \n\\* `read` - can read, but not write to or administer this project.  \n\\* `write` - can read and write, but not administer this project.  \n\\* `admin` - can read, write and administer this project.\""
}

func (c *ProjectsAddCollaboratorCmd) Run(isValueSetMap map[string]bool) error {
	c.SetIsValueSetMap(isValueSetMap)
	c.SetURLPath("/projects/:project_id/collaborators/:username")
	c.UpdatePreview("inertia", c.Inertia)
	c.UpdateURLPath("project_id", c.ProjectId)
	c.UpdateURLPath("username", c.Username)
	c.UpdateBody("permission", c.Permission)
	return c.DoRequest("PUT")
}

type ProjectsRemoveCollaboratorCmd struct {
	internal.BaseCmd
	Inertia   bool   "name:\"inertia-preview\" required:\"\" help:\"The Projects API is currently available for developers to preview. During the preview period, the API may change without advance notice. Please see the [blog post](/changes/2016-10-27-changes-to-projects-api) for full details. To access the API during the preview period, you must provide a custom [media type](/v3/media) in the `Accept` header:\n\n```\n  application/vnd.github.inertia-preview+json\n\n```\""
	ProjectId int64  `required:"" name:"project_id"`
	Username  string `required:"" name:"username"`
}

func (c *ProjectsRemoveCollaboratorCmd) Run(isValueSetMap map[string]bool) error {
	c.SetIsValueSetMap(isValueSetMap)
	c.SetURLPath("/projects/:project_id/collaborators/:username")
	c.UpdatePreview("inertia", c.Inertia)
	c.UpdateURLPath("project_id", c.ProjectId)
	c.UpdateURLPath("username", c.Username)
	return c.DoRequest("DELETE")
}

type ProjectsListColumnsCmd struct {
	internal.BaseCmd
	Inertia   bool  "name:\"inertia-preview\" required:\"\" help:\"The Projects API is currently available for developers to preview. During the preview period, the API may change without advance notice. Please see the [blog post](/changes/2016-10-27-changes-to-projects-api) for full details. To access the API during the preview period, you must provide a custom [media type](/v3/media) in the `Accept` header:\n\n```\n  application/vnd.github.inertia-preview+json\n\n```\""
	ProjectId int64 `required:"" name:"project_id"`
	PerPage   int64 `name:"per_page" help:"Results per page (max 100)"`
	Page      int64 `name:"page" help:"Page number of the results to fetch."`
}

func (c *ProjectsListColumnsCmd) Run(isValueSetMap map[string]bool) error {
	c.SetIsValueSetMap(isValueSetMap)
	c.SetURLPath("/projects/:project_id/columns")
	c.UpdatePreview("inertia", c.Inertia)
	c.UpdateURLPath("project_id", c.ProjectId)
	c.UpdateURLQuery("per_page", c.PerPage)
	c.UpdateURLQuery("page", c.Page)
	return c.DoRequest("GET")
}

type ProjectsGetColumnCmd struct {
	internal.BaseCmd
	Inertia  bool  "name:\"inertia-preview\" required:\"\" help:\"The Projects API is currently available for developers to preview. During the preview period, the API may change without advance notice. Please see the [blog post](/changes/2016-10-27-changes-to-projects-api) for full details. To access the API during the preview period, you must provide a custom [media type](/v3/media) in the `Accept` header:\n\n```\n  application/vnd.github.inertia-preview+json\n\n```\""
	ColumnId int64 `required:"" name:"column_id"`
}

func (c *ProjectsGetColumnCmd) Run(isValueSetMap map[string]bool) error {
	c.SetIsValueSetMap(isValueSetMap)
	c.SetURLPath("/projects/columns/:column_id")
	c.UpdatePreview("inertia", c.Inertia)
	c.UpdateURLPath("column_id", c.ColumnId)
	return c.DoRequest("GET")
}

type ProjectsCreateColumnCmd struct {
	internal.BaseCmd
	Inertia   bool   "name:\"inertia-preview\" required:\"\" help:\"The Projects API is currently available for developers to preview. During the preview period, the API may change without advance notice. Please see the [blog post](/changes/2016-10-27-changes-to-projects-api) for full details. To access the API during the preview period, you must provide a custom [media type](/v3/media) in the `Accept` header:\n\n```\n  application/vnd.github.inertia-preview+json\n\n```\""
	ProjectId int64  `required:"" name:"project_id"`
	Name      string `required:"" name:"name" help:"The name of the column."`
}

func (c *ProjectsCreateColumnCmd) Run(isValueSetMap map[string]bool) error {
	c.SetIsValueSetMap(isValueSetMap)
	c.SetURLPath("/projects/:project_id/columns")
	c.UpdatePreview("inertia", c.Inertia)
	c.UpdateURLPath("project_id", c.ProjectId)
	c.UpdateBody("name", c.Name)
	return c.DoRequest("POST")
}

type ProjectsUpdateColumnCmd struct {
	internal.BaseCmd
	Inertia  bool   "name:\"inertia-preview\" required:\"\" help:\"The Projects API is currently available for developers to preview. During the preview period, the API may change without advance notice. Please see the [blog post](/changes/2016-10-27-changes-to-projects-api) for full details. To access the API during the preview period, you must provide a custom [media type](/v3/media) in the `Accept` header:\n\n```\n  application/vnd.github.inertia-preview+json\n\n```\""
	ColumnId int64  `required:"" name:"column_id"`
	Name     string `required:"" name:"name" help:"The new name of the column."`
}

func (c *ProjectsUpdateColumnCmd) Run(isValueSetMap map[string]bool) error {
	c.SetIsValueSetMap(isValueSetMap)
	c.SetURLPath("/projects/columns/:column_id")
	c.UpdatePreview("inertia", c.Inertia)
	c.UpdateURLPath("column_id", c.ColumnId)
	c.UpdateBody("name", c.Name)
	return c.DoRequest("PATCH")
}

type ProjectsDeleteColumnCmd struct {
	internal.BaseCmd
	Inertia  bool  "name:\"inertia-preview\" required:\"\" help:\"The Projects API is currently available for developers to preview. During the preview period, the API may change without advance notice. Please see the [blog post](/changes/2016-10-27-changes-to-projects-api) for full details. To access the API during the preview period, you must provide a custom [media type](/v3/media) in the `Accept` header:\n\n```\n  application/vnd.github.inertia-preview+json\n\n```\""
	ColumnId int64 `required:"" name:"column_id"`
}

func (c *ProjectsDeleteColumnCmd) Run(isValueSetMap map[string]bool) error {
	c.SetIsValueSetMap(isValueSetMap)
	c.SetURLPath("/projects/columns/:column_id")
	c.UpdatePreview("inertia", c.Inertia)
	c.UpdateURLPath("column_id", c.ColumnId)
	return c.DoRequest("DELETE")
}

type ProjectsMoveColumnCmd struct {
	internal.BaseCmd
	Inertia  bool   "name:\"inertia-preview\" required:\"\" help:\"The Projects API is currently available for developers to preview. During the preview period, the API may change without advance notice. Please see the [blog post](/changes/2016-10-27-changes-to-projects-api) for full details. To access the API during the preview period, you must provide a custom [media type](/v3/media) in the `Accept` header:\n\n```\n  application/vnd.github.inertia-preview+json\n\n```\""
	ColumnId int64  `required:"" name:"column_id"`
	Position string "required:\"\" name:\"position\" help:\"Can be one of `first`, `last`, or `after:<column_id>`, where `<column_id>` is the `id` value of a column in the same project.\""
}

func (c *ProjectsMoveColumnCmd) Run(isValueSetMap map[string]bool) error {
	c.SetIsValueSetMap(isValueSetMap)
	c.SetURLPath("/projects/columns/:column_id/moves")
	c.UpdatePreview("inertia", c.Inertia)
	c.UpdateURLPath("column_id", c.ColumnId)
	c.UpdateBody("position", c.Position)
	return c.DoRequest("POST")
}
