// Code generated by octo-cli/generator; DO NOT EDIT.

package services

type RateLimitCmd struct {
	Get RateLimitGetCmd `cmd:"" help:"Get your current rate limit status"`
}

type RateLimitGetCmd struct {
	baseCmd
}

func (c *RateLimitGetCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/rate_limit"
	return c.doRequest("GET")
}
