// Code generated by go-github-cli/generator; DO NOT EDIT

package services

type UsersCmd struct {
	GetByUsername                     UsersGetByUsernameCmd                     `cmd:"" help:"Get a single user"`
	GetAuthenticated                  UsersGetAuthenticatedCmd                  `cmd:"" help:"Get the authenticated user"`
	UpdateAuthenticated               UsersUpdateAuthenticatedCmd               `cmd:"" help:"Update the authenticated user"`
	GetContextForUser                 UsersGetContextForUserCmd                 `cmd:"" help:"Get contextual information about a user"`
	List                              UsersListCmd                              `cmd:"" help:"Get all users"`
	ListBlocked                       UsersListBlockedCmd                       `cmd:"" help:"List blocked users"`
	CheckBlocked                      UsersCheckBlockedCmd                      `cmd:"" help:"Check whether you've blocked a user"`
	Block                             UsersBlockCmd                             `cmd:"" help:"Block a user"`
	Unblock                           UsersUnblockCmd                           `cmd:"" help:"Unblock a user"`
	ListEmails                        UsersListEmailsCmd                        `cmd:"" help:"List email addresses for a user"`
	ListPublicEmails                  UsersListPublicEmailsCmd                  `cmd:"" help:"List public email addresses for a user"`
	AddEmails                         UsersAddEmailsCmd                         `cmd:"" help:"Add email address(es)"`
	DeleteEmails                      UsersDeleteEmailsCmd                      `cmd:"" help:"Delete email address(es)"`
	TogglePrimaryEmailVisibility      UsersTogglePrimaryEmailVisibilityCmd      `cmd:"" help:"Toggle primary email visibility"`
	ListFollowersForUser              UsersListFollowersForUserCmd              `cmd:"" help:"List a user's followers"`
	ListFollowersForAuthenticatedUser UsersListFollowersForAuthenticatedUserCmd `cmd:"" help:"List the authenticated user's followers"`
	ListFollowingForUser              UsersListFollowingForUserCmd              `cmd:"" help:"List who a user is following"`
	ListFollowingForAuthenticatedUser UsersListFollowingForAuthenticatedUserCmd `cmd:"" help:"List who the authenticated user is following"`
	CheckFollowing                    UsersCheckFollowingCmd                    `cmd:"" help:"Check if you are following a user"`
	CheckFollowingForUser             UsersCheckFollowingForUserCmd             `cmd:"" help:"Check if one user follows another"`
	Follow                            UsersFollowCmd                            `cmd:"" help:"Follow a user"`
	Unfollow                          UsersUnfollowCmd                          `cmd:"" help:"Unfollow a user"`
	ListPublicKeysForUser             UsersListPublicKeysForUserCmd             `cmd:"" help:"List public keys for a user"`
	ListPublicKeys                    UsersListPublicKeysCmd                    `cmd:"" help:"List your public keys"`
	GetPublicKey                      UsersGetPublicKeyCmd                      `cmd:"" help:"Get a single public key"`
	CreatePublicKey                   UsersCreatePublicKeyCmd                   `cmd:"" help:"Create a public key"`
	DeletePublicKey                   UsersDeletePublicKeyCmd                   `cmd:"" help:"Delete a public key"`
	ListGpgKeysForUser                UsersListGpgKeysForUserCmd                `cmd:"" help:"List GPG keys for a user"`
	ListGpgKeys                       UsersListGpgKeysCmd                       `cmd:"" help:"List your GPG keys"`
	GetGpgKey                         UsersGetGpgKeyCmd                         `cmd:"" help:"Get a single GPG key"`
	CreateGpgKey                      UsersCreateGpgKeyCmd                      `cmd:"" help:"Create a GPG key"`
	DeleteGpgKey                      UsersDeleteGpgKeyCmd                      `cmd:"" help:"Delete a GPG key"`
}

type UsersGetByUsernameCmd struct {
	baseCmd
	Username string `required:"" name:"username"`
}

func (c *UsersGetByUsernameCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/users/:username"
	c.updateURLPath("username", c.Username)
	return c.doRequest("GET")
}

type UsersGetAuthenticatedCmd struct {
	baseCmd
}

func (c *UsersGetAuthenticatedCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/user"
	return c.doRequest("GET")
}

type UsersUpdateAuthenticatedCmd struct {
	baseCmd
	Name     string `name:"name" help:"The new name of the user."`
	Email    string `name:"email" help:"The publicly visible email address of the user."`
	Blog     string `name:"blog" help:"The new blog URL of the user."`
	Company  string `name:"company" help:"The new company of the user."`
	Location string `name:"location" help:"The new location of the user."`
	Hireable bool   `name:"hireable" help:"The new hiring availability of the user."`
	Bio      string `name:"bio" help:"The new short biography of the user."`
}

func (c *UsersUpdateAuthenticatedCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/user"
	c.updateBody("name", c.Name)
	c.updateBody("email", c.Email)
	c.updateBody("blog", c.Blog)
	c.updateBody("company", c.Company)
	c.updateBody("location", c.Location)
	c.updateBody("hireable", c.Hireable)
	c.updateBody("bio", c.Bio)
	return c.doRequest("PATCH")
}

type UsersGetContextForUserCmd struct {
	baseCmd
	Username    string `required:"" name:"username"`
	SubjectType string "name:\"subject_type\" help:\"Identifies which additional information you'd like to receive about the person's hovercard. Can be `organization`, `repository`, `issue`, `pull_request`. **Required** when using `subject_id`.\""
	SubjectId   string "name:\"subject_id\" help:\"Uses the ID for the `subject_type` you specified. **Required** when using `subject_type`.\""
}

func (c *UsersGetContextForUserCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/users/:username/hovercard"
	c.updateURLPath("username", c.Username)
	c.updateURLQuery("subject_type", c.SubjectType)
	c.updateURLQuery("subject_id", c.SubjectId)
	return c.doRequest("GET")
}

type UsersListCmd struct {
	baseCmd
	Since   string `name:"since" help:"The integer ID of the last User that you've seen."`
	PerPage int64  `name:"per_page" help:"Results per page (max 100)"`
	Page    int64  `name:"page" help:"Page number of the results to fetch."`
}

func (c *UsersListCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/users"
	c.updateURLQuery("since", c.Since)
	c.updateURLQuery("per_page", c.PerPage)
	c.updateURLQuery("page", c.Page)
	return c.doRequest("GET")
}

type UsersListBlockedCmd struct {
	baseCmd
}

func (c *UsersListBlockedCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/user/blocks"
	return c.doRequest("GET")
}

type UsersCheckBlockedCmd struct {
	baseCmd
	Username string `required:"" name:"username"`
}

func (c *UsersCheckBlockedCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/user/blocks/:username"
	c.updateURLPath("username", c.Username)
	return c.doRequest("GET")
}

type UsersBlockCmd struct {
	baseCmd
	Username string `required:"" name:"username"`
}

func (c *UsersBlockCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/user/blocks/:username"
	c.updateURLPath("username", c.Username)
	return c.doRequest("PUT")
}

type UsersUnblockCmd struct {
	baseCmd
	Username string `required:"" name:"username"`
}

func (c *UsersUnblockCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/user/blocks/:username"
	c.updateURLPath("username", c.Username)
	return c.doRequest("DELETE")
}

type UsersListEmailsCmd struct {
	baseCmd
	PerPage int64 `name:"per_page" help:"Results per page (max 100)"`
	Page    int64 `name:"page" help:"Page number of the results to fetch."`
}

func (c *UsersListEmailsCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/user/emails"
	c.updateURLQuery("per_page", c.PerPage)
	c.updateURLQuery("page", c.Page)
	return c.doRequest("GET")
}

type UsersListPublicEmailsCmd struct {
	baseCmd
	PerPage int64 `name:"per_page" help:"Results per page (max 100)"`
	Page    int64 `name:"page" help:"Page number of the results to fetch."`
}

func (c *UsersListPublicEmailsCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/user/public_emails"
	c.updateURLQuery("per_page", c.PerPage)
	c.updateURLQuery("page", c.Page)
	return c.doRequest("GET")
}

type UsersAddEmailsCmd struct {
	baseCmd
	Emails []string "required:\"\" name:\"emails\" help:\"Adds one or more email addresses to your GitHub account. Must contain at least one email address. **Note:** Alternatively, you can pass a single email address or an `array` of emails addresses directly, but we recommend that you pass an object using the `emails` key.\""
}

func (c *UsersAddEmailsCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/user/emails"
	c.updateBody("emails", c.Emails)
	return c.doRequest("POST")
}

type UsersDeleteEmailsCmd struct {
	baseCmd
	Emails []string "required:\"\" name:\"emails\" help:\"Deletes one or more email addresses from your GitHub account. Must contain at least one email address. **Note:** Alternatively, you can pass a single email address or an `array` of emails addresses directly, but we recommend that you pass an object using the `emails` key.\""
}

func (c *UsersDeleteEmailsCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/user/emails"
	c.updateBody("emails", c.Emails)
	return c.doRequest("DELETE")
}

type UsersTogglePrimaryEmailVisibilityCmd struct {
	baseCmd
	Email      string `required:"" name:"email" help:"Specify the _primary_ email address that needs a visibility change."`
	Visibility string "required:\"\" name:\"visibility\" help:\"Use `public` to enable an authenticated user to view the specified email address, or use `private` so this primary email address cannot be seen publicly.\""
}

func (c *UsersTogglePrimaryEmailVisibilityCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/user/email/visibility"
	c.updateBody("email", c.Email)
	c.updateBody("visibility", c.Visibility)
	return c.doRequest("PATCH")
}

type UsersListFollowersForUserCmd struct {
	baseCmd
	Username string `required:"" name:"username"`
	PerPage  int64  `name:"per_page" help:"Results per page (max 100)"`
	Page     int64  `name:"page" help:"Page number of the results to fetch."`
}

func (c *UsersListFollowersForUserCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/users/:username/followers"
	c.updateURLPath("username", c.Username)
	c.updateURLQuery("per_page", c.PerPage)
	c.updateURLQuery("page", c.Page)
	return c.doRequest("GET")
}

type UsersListFollowersForAuthenticatedUserCmd struct {
	baseCmd
	PerPage int64 `name:"per_page" help:"Results per page (max 100)"`
	Page    int64 `name:"page" help:"Page number of the results to fetch."`
}

func (c *UsersListFollowersForAuthenticatedUserCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/user/followers"
	c.updateURLQuery("per_page", c.PerPage)
	c.updateURLQuery("page", c.Page)
	return c.doRequest("GET")
}

type UsersListFollowingForUserCmd struct {
	baseCmd
	Username string `required:"" name:"username"`
	PerPage  int64  `name:"per_page" help:"Results per page (max 100)"`
	Page     int64  `name:"page" help:"Page number of the results to fetch."`
}

func (c *UsersListFollowingForUserCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/users/:username/following"
	c.updateURLPath("username", c.Username)
	c.updateURLQuery("per_page", c.PerPage)
	c.updateURLQuery("page", c.Page)
	return c.doRequest("GET")
}

type UsersListFollowingForAuthenticatedUserCmd struct {
	baseCmd
	PerPage int64 `name:"per_page" help:"Results per page (max 100)"`
	Page    int64 `name:"page" help:"Page number of the results to fetch."`
}

func (c *UsersListFollowingForAuthenticatedUserCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/user/following"
	c.updateURLQuery("per_page", c.PerPage)
	c.updateURLQuery("page", c.Page)
	return c.doRequest("GET")
}

type UsersCheckFollowingCmd struct {
	baseCmd
	Username string `required:"" name:"username"`
}

func (c *UsersCheckFollowingCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/user/following/:username"
	c.updateURLPath("username", c.Username)
	return c.doRequest("GET")
}

type UsersCheckFollowingForUserCmd struct {
	baseCmd
	Username   string `required:"" name:"username"`
	TargetUser string `required:"" name:"target_user"`
}

func (c *UsersCheckFollowingForUserCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/users/:username/following/:target_user"
	c.updateURLPath("username", c.Username)
	c.updateURLPath("target_user", c.TargetUser)
	return c.doRequest("GET")
}

type UsersFollowCmd struct {
	baseCmd
	Username string `required:"" name:"username"`
}

func (c *UsersFollowCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/user/following/:username"
	c.updateURLPath("username", c.Username)
	return c.doRequest("PUT")
}

type UsersUnfollowCmd struct {
	baseCmd
	Username string `required:"" name:"username"`
}

func (c *UsersUnfollowCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/user/following/:username"
	c.updateURLPath("username", c.Username)
	return c.doRequest("DELETE")
}

type UsersListPublicKeysForUserCmd struct {
	baseCmd
	Username string `required:"" name:"username"`
	PerPage  int64  `name:"per_page" help:"Results per page (max 100)"`
	Page     int64  `name:"page" help:"Page number of the results to fetch."`
}

func (c *UsersListPublicKeysForUserCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/users/:username/keys"
	c.updateURLPath("username", c.Username)
	c.updateURLQuery("per_page", c.PerPage)
	c.updateURLQuery("page", c.Page)
	return c.doRequest("GET")
}

type UsersListPublicKeysCmd struct {
	baseCmd
	PerPage int64 `name:"per_page" help:"Results per page (max 100)"`
	Page    int64 `name:"page" help:"Page number of the results to fetch."`
}

func (c *UsersListPublicKeysCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/user/keys"
	c.updateURLQuery("per_page", c.PerPage)
	c.updateURLQuery("page", c.Page)
	return c.doRequest("GET")
}

type UsersGetPublicKeyCmd struct {
	baseCmd
	KeyId int64 `required:"" name:"key_id"`
}

func (c *UsersGetPublicKeyCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/user/keys/:key_id"
	c.updateURLPath("key_id", c.KeyId)
	return c.doRequest("GET")
}

type UsersCreatePublicKeyCmd struct {
	baseCmd
	Title string `name:"title" help:"A descriptive name for the new key. Use a name that will help you recognize this key in your GitHub account. For example, if you're using a personal Mac, you might call this key 'Personal MacBook Air'."`
	Key   string `name:"key" help:"The public SSH key to add to your GitHub account. See '[Generating a new SSH key](https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/)' for guidance on how to create a public SSH key."`
}

func (c *UsersCreatePublicKeyCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/user/keys"
	c.updateBody("title", c.Title)
	c.updateBody("key", c.Key)
	return c.doRequest("POST")
}

type UsersDeletePublicKeyCmd struct {
	baseCmd
	KeyId int64 `required:"" name:"key_id"`
}

func (c *UsersDeletePublicKeyCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/user/keys/:key_id"
	c.updateURLPath("key_id", c.KeyId)
	return c.doRequest("DELETE")
}

type UsersListGpgKeysForUserCmd struct {
	baseCmd
	Username string `required:"" name:"username"`
	PerPage  int64  `name:"per_page" help:"Results per page (max 100)"`
	Page     int64  `name:"page" help:"Page number of the results to fetch."`
}

func (c *UsersListGpgKeysForUserCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/users/:username/gpg_keys"
	c.updateURLPath("username", c.Username)
	c.updateURLQuery("per_page", c.PerPage)
	c.updateURLQuery("page", c.Page)
	return c.doRequest("GET")
}

type UsersListGpgKeysCmd struct {
	baseCmd
	PerPage int64 `name:"per_page" help:"Results per page (max 100)"`
	Page    int64 `name:"page" help:"Page number of the results to fetch."`
}

func (c *UsersListGpgKeysCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/user/gpg_keys"
	c.updateURLQuery("per_page", c.PerPage)
	c.updateURLQuery("page", c.Page)
	return c.doRequest("GET")
}

type UsersGetGpgKeyCmd struct {
	baseCmd
	GpgKeyId int64 `required:"" name:"gpg_key_id"`
}

func (c *UsersGetGpgKeyCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/user/gpg_keys/:gpg_key_id"
	c.updateURLPath("gpg_key_id", c.GpgKeyId)
	return c.doRequest("GET")
}

type UsersCreateGpgKeyCmd struct {
	baseCmd
	ArmoredPublicKey string `name:"armored_public_key" help:"Your GPG key, generated in ASCII-armored format. See '[Generating a new GPG key](https://help.github.com/articles/generating-a-new-gpg-key/)' for help creating a GPG key."`
}

func (c *UsersCreateGpgKeyCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/user/gpg_keys"
	c.updateBody("armored_public_key", c.ArmoredPublicKey)
	return c.doRequest("POST")
}

type UsersDeleteGpgKeyCmd struct {
	baseCmd
	GpgKeyId int64 `required:"" name:"gpg_key_id"`
}

func (c *UsersDeleteGpgKeyCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/user/gpg_keys/:gpg_key_id"
	c.updateURLPath("gpg_key_id", c.GpgKeyId)
	return c.doRequest("DELETE")
}
