#!/bin/sh

set -ex

CDPATH="" cd -- "$(dirname -- "$(dirname -- "$0")")"

mkdir -p bin

[ -f bin/bindown ] || sh -c "$(curl -sfL https://github.com/WillAbides/bindown/releases/download/v3.3.3/bootstrap-bindown.sh)"
ls -haltr bin
exec bin/bindown "$@"
