#!/bin/sh

# Exit if any subcommand fails
set -e

# Ensure we're always running from the project root
cd "$(dirname "$0")/.."

go build -o bin/go-github-cli -ldflags "-X main.version=${VERSION:-development}"
