#!/bin/sh

set -e

CDPATH="" cd -- "$(dirname -- "$(dirname -- "$0")")"

make -s bin/octo
touch ./current-schema-tag.txt

git diff --stat --exit-code current-schema-tag.txt || (echo "clean your tree before proceeding" && exit 1)

script/update-schema

updated=
git diff --stat --exit-code current-schema-tag.txt || updated=1
if [ -z "$updated" ]; then
  echo "already up to date"
  exit
fi

new_version="$(cat current-schema-tag.txt)"
update_branch="update-schema-release-$new_version"

pullcount="$(
  bin/octo pulls list \
    --repo octo-cli/octo-cli \
    --head "octo-cli:$update_branch" \
    --format "{{len .}}"
)"

# exit if there's already a pr for this update
[ "$pullcount" != "0" ] && echo "pr already exists for $update_branch" && exit

git checkout -b "$update_branch"

script/generate
script/update-docs

git add README.md api.github.com.json current-schema-tag.txt docs/ internal/generated/

[ -z "$(git config --get user.name)" ] && git config user.name "octo-cli bot"
[ -z "$(git config --get user.email)" ] && git config user.email "octo-cli-bot@local"

git commit -m "update to schema $new_version"
git push --set-upstream origin "$update_branch"

bin/octo pulls create \
  --base main \
  --head "$update_branch" \
  --repo octo-cli/octo-cli \
  --title "Update to schema $new_version" \
  --body "There's a new openapi schema. Here's a PR with the changes."
