#!/bin/sh

set -e

CDPATH="" cd -- "$(dirname -- "$(dirname -- "$0")")"
make -s bin/buildtool

mkdir -p ./internal/generator/testdata/generated

cp ./api.github.com.json ./internal/generator/testdata/routes.json
script/generate \
  --routes-path ./internal/generator/testdata/routes.json \
  --output-path ./internal/generator/testdata/generated \
  --docs-path ./internal/generator/testdata/docs
