#!/bin/sh

set -e

CDPATH="" cd -- "$(dirname -- "$(dirname -- "$0")")"

make -s bin/octo
touch ./current-schema-tag.txt
current_tag="$(cat current-schema-tag.txt)"
latest_tag="$(bin/octo repos get-latest-release --repo octokit/routes --format "{{.tag_name}}")"
[ "$current_tag" = "$latest_tag" ] && exit
url="https://github.com/octokit/routes/releases/download/$latest_tag/api.github.com.json"
curl -sOL "$url"
printf "%s" "$latest_tag" > ./current-schema-tag.txt
