#!/bin/sh

set -e

CDPATH="" cd -- "$(dirname -- "$(dirname -- "$0")")"

get_latest_version() {
  script/octo repos get-latest-release --repo github/rest-api-description --format '{{.tag_name}}'
}

touch ./current-schema-tag.txt
current_version="$(cat current-schema-tag.txt)"
TARGET_SCHEMA_VERSION="${TARGET_SCHEMA_VERSION:-$(get_latest_version)}"
[ "$current_version" = "$TARGET_SCHEMA_VERSION" ] && exit

# https://raw.githubusercontent.com/github/rest-api-description/%s/descriptions/api.github.com/api.github.com.json
curl -sOL "https://raw.githubusercontent.com/github/rest-api-description/${TARGET_SCHEMA_VERSION}/descriptions/api.github.com/api.github.com.json"
printf "%s" "$TARGET_SCHEMA_VERSION" > ./current-schema-tag.txt
