#!/bin/sh

set -e

CDPATH="" cd -- "$(dirname -- "$(dirname -- "$0")")"

mkdir -p ./internal/generator/testdata/generated

cp ./api.github.com.json ./internal/generator/testdata/routes.json

go run ./codegen.go \
  -schema ./internal/generator/testdata/routes.json \
  -out ./internal/generator/testdata/generated

go run ./docgen.go \
 -schema ./internal/generator/testdata/routes.json \
 -out ./internal/generator/testdata/docs
