#!/bin/sh

set -e

CDPATH="" cd -- "$(dirname -- "$(dirname -- "$0")")"

if [ "$1" = "--check" ]; then
  [ -z "$(git status --porcelain)" ] || {
    git status
    1>&2 echo "Running 'script/update-docs --check' requires a clean git working tree. Please commit or stash changes and try again."
    exit 1
  }
  script/update-docs
  [ -z "$(git status --porcelain)" ] || {
    git status
    1>&2 echo "script/update-docs resulted in changes. Please commit changes (or 'git reset --hard HEAD' if you aren't ready to commit changes)."
    git diff
    exit 1
  }
  exit 0
fi

go run ./docgen.go -schema api.github.com.json -out ./docs
cp README.md docs/README.md
cp CONTRIBUTING.md docs/CONTRIBUTING.md
