// Code generated by ghx generator DO NOT EDIT
package organizationssvc

import (
	"context"
	"encoding/json"

	"github.com/alecthomas/kong"
	"github.com/google/go-github/github"
	"golang.org/x/oauth2"
)

type OrganizationsCmd struct {
	Get OrganizationsGetCmd `cmd:"" help:"Get an organization"`
}

type OrganizationsGetCmd struct {
	Token string `env:"GITHUB_TOKEN" required:""`
	Org   string `required:""`
}

func (c *OrganizationsGetCmd) Run(k *kong.Context) error {
	ctx := context.Background()
	ts := oauth2.StaticTokenSource(&oauth2.Token{AccessToken: c.Token})
	tc := oauth2.NewClient(ctx, ts)
	client := github.NewClient(tc)
	element, _, err := client.Organizations.Get(ctx, c.Org)
	if err != nil {
		return err
	}
	return json.NewEncoder(k.Stdout).Encode(element)
}
