// Code generated by octo-cli/generator; DO NOT EDIT.

package services

type MarkdownCmd struct {
	Render    MarkdownRenderCmd    `cmd:"" help:"Render an arbitrary Markdown document"`
	RenderRaw MarkdownRenderRawCmd `cmd:"" help:"Render a Markdown document in raw mode"`
}

type MarkdownRenderCmd struct {
	baseCmd
	Text    string `required:"" name:"text" help:"The Markdown text to render in HTML. Markdown content must be 400 KB or less."`
	Mode    string "name:\"mode\" help:\"The rendering mode. Can be either:  \n\\* `markdown` to render a document in plain Markdown, just like README.md files are rendered.  \n\\* `gfm` to render a document in [GitHub Flavored Markdown](https://github.github.com/gfm/), which creates links for user mentions as well as references to SHA-1 hashes, issues, and pull requests.\""
	Context string "name:\"context\" help:\"The repository context to use when creating references in `gfm` mode. Omit this parameter when using `markdown` mode.\""
}

func (c *MarkdownRenderCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/markdown"
	c.updateBody("text", c.Text)
	c.updateBody("mode", c.Mode)
	c.updateBody("context", c.Context)
	return c.doRequest("POST")
}

type MarkdownRenderRawCmd struct {
	baseCmd
	Data string `required:"" name:"data"`
}

func (c *MarkdownRenderRawCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/markdown/raw"
	c.updateBody("data", c.Data)
	return c.doRequest("POST")
}
