// Code generated by octo-cli/generator; DO NOT EDIT.

package services

type ReactionsCmd struct {
	ListForCommitComment              ReactionsListForCommitCommentCmd              `cmd:"" help:"List reactions for a commit comment"`
	CreateForCommitComment            ReactionsCreateForCommitCommentCmd            `cmd:"" help:"Create reaction for a commit comment"`
	ListForIssue                      ReactionsListForIssueCmd                      `cmd:"" help:"List reactions for an issue"`
	CreateForIssue                    ReactionsCreateForIssueCmd                    `cmd:"" help:"Create reaction for an issue"`
	ListForIssueComment               ReactionsListForIssueCommentCmd               `cmd:"" help:"List reactions for an issue comment"`
	CreateForIssueComment             ReactionsCreateForIssueCommentCmd             `cmd:"" help:"Create reaction for an issue comment"`
	ListForPullRequestReviewComment   ReactionsListForPullRequestReviewCommentCmd   `cmd:"" help:"List reactions for a pull request review comment"`
	CreateForPullRequestReviewComment ReactionsCreateForPullRequestReviewCommentCmd `cmd:"" help:"Create reaction for a pull request review comment"`
	ListForTeamDiscussion             ReactionsListForTeamDiscussionCmd             `cmd:"" help:"List reactions for a team discussion"`
	CreateForTeamDiscussion           ReactionsCreateForTeamDiscussionCmd           `cmd:"" help:"Create reaction for a team discussion"`
	ListForTeamDiscussionComment      ReactionsListForTeamDiscussionCommentCmd      `cmd:"" help:"List reactions for a team discussion comment"`
	CreateForTeamDiscussionComment    ReactionsCreateForTeamDiscussionCommentCmd    `cmd:"" help:"Create reaction for a team discussion comment"`
	Delete                            ReactionsDeleteCmd                            `cmd:"" help:"Delete a reaction"`
}

type ReactionsListForCommitCommentCmd struct {
	baseCmd
	SquirrelGirl bool   "name:\"squirrel-girl-preview\" required:\"\" help:\"**Note:** APIs for managing reactions are currently available for developers to preview. See the [blog post](/changes/2016-05-12-reactions-api-preview) for full details. To access the API during the preview period, you must provide a custom [media type](/v3/media) in the `Accept` header:\n\n```\n  application/vnd.github.squirrel-girl-preview+json\n\n```\""
	Owner        string `required:"" name:"owner"`
	Repo         string `required:"" name:"repo"`
	CommentId    int64  `required:"" name:"comment_id"`
	Content      string `name:"content" help:"Returns a single [reaction type](https://developer.github.com/v3/reactions/#reaction-types). Omit this parameter to list all reactions to a commit comment."`
	PerPage      int64  `name:"per_page" help:"Results per page (max 100)"`
	Page         int64  `name:"page" help:"Page number of the results to fetch."`
}

func (c *ReactionsListForCommitCommentCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/repos/:owner/:repo/comments/:comment_id/reactions"
	c.updatePreview("squirrel-girl", c.SquirrelGirl)
	c.updateURLPath("owner", c.Owner)
	c.updateURLPath("repo", c.Repo)
	c.updateURLPath("comment_id", c.CommentId)
	c.updateURLQuery("content", c.Content)
	c.updateURLQuery("per_page", c.PerPage)
	c.updateURLQuery("page", c.Page)
	return c.doRequest("GET")
}

type ReactionsCreateForCommitCommentCmd struct {
	baseCmd
	SquirrelGirl bool   "name:\"squirrel-girl-preview\" required:\"\" help:\"**Note:** APIs for managing reactions are currently available for developers to preview. See the [blog post](/changes/2016-05-12-reactions-api-preview) for full details. To access the API during the preview period, you must provide a custom [media type](/v3/media) in the `Accept` header:\n\n```\n  application/vnd.github.squirrel-girl-preview+json\n\n```\""
	Owner        string `required:"" name:"owner"`
	Repo         string `required:"" name:"repo"`
	CommentId    int64  `required:"" name:"comment_id"`
	Content      string `required:"" name:"content" help:"The [reaction type](https://developer.github.com/v3/reactions/#reaction-types) to add to the commit comment."`
}

func (c *ReactionsCreateForCommitCommentCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/repos/:owner/:repo/comments/:comment_id/reactions"
	c.updatePreview("squirrel-girl", c.SquirrelGirl)
	c.updateURLPath("owner", c.Owner)
	c.updateURLPath("repo", c.Repo)
	c.updateURLPath("comment_id", c.CommentId)
	c.updateBody("content", c.Content)
	return c.doRequest("POST")
}

type ReactionsListForIssueCmd struct {
	baseCmd
	SquirrelGirl bool   "name:\"squirrel-girl-preview\" required:\"\" help:\"**Note:** APIs for managing reactions are currently available for developers to preview. See the [blog post](/changes/2016-05-12-reactions-api-preview) for full details. To access the API during the preview period, you must provide a custom [media type](/v3/media) in the `Accept` header:\n\n```\n  application/vnd.github.squirrel-girl-preview+json\n\n```\""
	Owner        string `required:"" name:"owner"`
	Repo         string `required:"" name:"repo"`
	Number       int64  `required:"" name:"number"`
	Content      string `name:"content" help:"Returns a single [reaction type](https://developer.github.com/v3/reactions/#reaction-types). Omit this parameter to list all reactions to an issue."`
	PerPage      int64  `name:"per_page" help:"Results per page (max 100)"`
	Page         int64  `name:"page" help:"Page number of the results to fetch."`
}

func (c *ReactionsListForIssueCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/repos/:owner/:repo/issues/:number/reactions"
	c.updatePreview("squirrel-girl", c.SquirrelGirl)
	c.updateURLPath("owner", c.Owner)
	c.updateURLPath("repo", c.Repo)
	c.updateURLPath("number", c.Number)
	c.updateURLQuery("content", c.Content)
	c.updateURLQuery("per_page", c.PerPage)
	c.updateURLQuery("page", c.Page)
	return c.doRequest("GET")
}

type ReactionsCreateForIssueCmd struct {
	baseCmd
	SquirrelGirl bool   "name:\"squirrel-girl-preview\" required:\"\" help:\"**Note:** APIs for managing reactions are currently available for developers to preview. See the [blog post](/changes/2016-05-12-reactions-api-preview) for full details. To access the API during the preview period, you must provide a custom [media type](/v3/media) in the `Accept` header:\n\n```\n  application/vnd.github.squirrel-girl-preview+json\n\n```\""
	Owner        string `required:"" name:"owner"`
	Repo         string `required:"" name:"repo"`
	Number       int64  `required:"" name:"number"`
	Content      string `required:"" name:"content" help:"The [reaction type](https://developer.github.com/v3/reactions/#reaction-types) to add to the issue."`
}

func (c *ReactionsCreateForIssueCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/repos/:owner/:repo/issues/:number/reactions"
	c.updatePreview("squirrel-girl", c.SquirrelGirl)
	c.updateURLPath("owner", c.Owner)
	c.updateURLPath("repo", c.Repo)
	c.updateURLPath("number", c.Number)
	c.updateBody("content", c.Content)
	return c.doRequest("POST")
}

type ReactionsListForIssueCommentCmd struct {
	baseCmd
	SquirrelGirl bool   "name:\"squirrel-girl-preview\" required:\"\" help:\"**Note:** APIs for managing reactions are currently available for developers to preview. See the [blog post](/changes/2016-05-12-reactions-api-preview) for full details. To access the API during the preview period, you must provide a custom [media type](/v3/media) in the `Accept` header:\n\n```\n  application/vnd.github.squirrel-girl-preview+json\n\n```\""
	Owner        string `required:"" name:"owner"`
	Repo         string `required:"" name:"repo"`
	CommentId    int64  `required:"" name:"comment_id"`
	Content      string `name:"content" help:"Returns a single [reaction type](https://developer.github.com/v3/reactions/#reaction-types). Omit this parameter to list all reactions to an issue comment."`
	PerPage      int64  `name:"per_page" help:"Results per page (max 100)"`
	Page         int64  `name:"page" help:"Page number of the results to fetch."`
}

func (c *ReactionsListForIssueCommentCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/repos/:owner/:repo/issues/comments/:comment_id/reactions"
	c.updatePreview("squirrel-girl", c.SquirrelGirl)
	c.updateURLPath("owner", c.Owner)
	c.updateURLPath("repo", c.Repo)
	c.updateURLPath("comment_id", c.CommentId)
	c.updateURLQuery("content", c.Content)
	c.updateURLQuery("per_page", c.PerPage)
	c.updateURLQuery("page", c.Page)
	return c.doRequest("GET")
}

type ReactionsCreateForIssueCommentCmd struct {
	baseCmd
	SquirrelGirl bool   "name:\"squirrel-girl-preview\" required:\"\" help:\"**Note:** APIs for managing reactions are currently available for developers to preview. See the [blog post](/changes/2016-05-12-reactions-api-preview) for full details. To access the API during the preview period, you must provide a custom [media type](/v3/media) in the `Accept` header:\n\n```\n  application/vnd.github.squirrel-girl-preview+json\n\n```\""
	Owner        string `required:"" name:"owner"`
	Repo         string `required:"" name:"repo"`
	CommentId    int64  `required:"" name:"comment_id"`
	Content      string `required:"" name:"content" help:"The [reaction type](https://developer.github.com/v3/reactions/#reaction-types) to add to the issue comment."`
}

func (c *ReactionsCreateForIssueCommentCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/repos/:owner/:repo/issues/comments/:comment_id/reactions"
	c.updatePreview("squirrel-girl", c.SquirrelGirl)
	c.updateURLPath("owner", c.Owner)
	c.updateURLPath("repo", c.Repo)
	c.updateURLPath("comment_id", c.CommentId)
	c.updateBody("content", c.Content)
	return c.doRequest("POST")
}

type ReactionsListForPullRequestReviewCommentCmd struct {
	baseCmd
	SquirrelGirl bool   "name:\"squirrel-girl-preview\" required:\"\" help:\"**Note:** APIs for managing reactions are currently available for developers to preview. See the [blog post](/changes/2016-05-12-reactions-api-preview) for full details. To access the API during the preview period, you must provide a custom [media type](/v3/media) in the `Accept` header:\n\n```\n  application/vnd.github.squirrel-girl-preview+json\n\n```\""
	Owner        string `required:"" name:"owner"`
	Repo         string `required:"" name:"repo"`
	CommentId    int64  `required:"" name:"comment_id"`
	Content      string `name:"content" help:"Returns a single [reaction type](https://developer.github.com/v3/reactions/#reaction-types). Omit this parameter to list all reactions to a pull request review comment."`
	PerPage      int64  `name:"per_page" help:"Results per page (max 100)"`
	Page         int64  `name:"page" help:"Page number of the results to fetch."`
}

func (c *ReactionsListForPullRequestReviewCommentCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/repos/:owner/:repo/pulls/comments/:comment_id/reactions"
	c.updatePreview("squirrel-girl", c.SquirrelGirl)
	c.updateURLPath("owner", c.Owner)
	c.updateURLPath("repo", c.Repo)
	c.updateURLPath("comment_id", c.CommentId)
	c.updateURLQuery("content", c.Content)
	c.updateURLQuery("per_page", c.PerPage)
	c.updateURLQuery("page", c.Page)
	return c.doRequest("GET")
}

type ReactionsCreateForPullRequestReviewCommentCmd struct {
	baseCmd
	SquirrelGirl bool   "name:\"squirrel-girl-preview\" required:\"\" help:\"**Note:** APIs for managing reactions are currently available for developers to preview. See the [blog post](/changes/2016-05-12-reactions-api-preview) for full details. To access the API during the preview period, you must provide a custom [media type](/v3/media) in the `Accept` header:\n\n```\n  application/vnd.github.squirrel-girl-preview+json\n\n```\""
	Owner        string `required:"" name:"owner"`
	Repo         string `required:"" name:"repo"`
	CommentId    int64  `required:"" name:"comment_id"`
	Content      string `required:"" name:"content" help:"The [reaction type](https://developer.github.com/v3/reactions/#reaction-types) to add to the pull request review comment."`
}

func (c *ReactionsCreateForPullRequestReviewCommentCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/repos/:owner/:repo/pulls/comments/:comment_id/reactions"
	c.updatePreview("squirrel-girl", c.SquirrelGirl)
	c.updateURLPath("owner", c.Owner)
	c.updateURLPath("repo", c.Repo)
	c.updateURLPath("comment_id", c.CommentId)
	c.updateBody("content", c.Content)
	return c.doRequest("POST")
}

type ReactionsListForTeamDiscussionCmd struct {
	baseCmd
	Echo             bool   "name:\"echo-preview\" required:\"\" help:\"**Note:** The team discussions API is currently available for developers to preview. See the [blog post](/changes/2018-02-07-team-discussions-api) for full details. To access the API during the preview period, you must provide a custom [media type](/v3/media) in the `Accept` header:\n\n```\napplication/vnd.github.echo-preview+json\n\n```\""
	SquirrelGirl     bool   "name:\"squirrel-girl-preview\" required:\"\" help:\"**Note:** APIs for managing reactions are currently available for developers to preview. See the [blog post](/changes/2016-05-12-reactions-api-preview) for full details. To access the API during the preview period, you must provide a custom [media type](/v3/media) in the `Accept` header:\n\n```\n  application/vnd.github.squirrel-girl-preview+json\n\n```\""
	TeamId           int64  `required:"" name:"team_id"`
	DiscussionNumber int64  `required:"" name:"discussion_number"`
	Content          string `name:"content" help:"Returns a single [reaction type](https://developer.github.com/v3/reactions/#reaction-types). Omit this parameter to list all reactions to a team discussion."`
	PerPage          int64  `name:"per_page" help:"Results per page (max 100)"`
	Page             int64  `name:"page" help:"Page number of the results to fetch."`
}

func (c *ReactionsListForTeamDiscussionCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/teams/:team_id/discussions/:discussion_number/reactions"
	c.updatePreview("echo", c.Echo)
	c.updatePreview("squirrel-girl", c.SquirrelGirl)
	c.updateURLPath("team_id", c.TeamId)
	c.updateURLPath("discussion_number", c.DiscussionNumber)
	c.updateURLQuery("content", c.Content)
	c.updateURLQuery("per_page", c.PerPage)
	c.updateURLQuery("page", c.Page)
	return c.doRequest("GET")
}

type ReactionsCreateForTeamDiscussionCmd struct {
	baseCmd
	Echo             bool   "name:\"echo-preview\" required:\"\" help:\"**Note:** The team discussions API is currently available for developers to preview. See the [blog post](/changes/2018-02-07-team-discussions-api) for full details. To access the API during the preview period, you must provide a custom [media type](/v3/media) in the `Accept` header:\n\n```\napplication/vnd.github.echo-preview+json\n\n```\""
	SquirrelGirl     bool   "name:\"squirrel-girl-preview\" required:\"\" help:\"**Note:** APIs for managing reactions are currently available for developers to preview. See the [blog post](/changes/2016-05-12-reactions-api-preview) for full details. To access the API during the preview period, you must provide a custom [media type](/v3/media) in the `Accept` header:\n\n```\n  application/vnd.github.squirrel-girl-preview+json\n\n```\""
	TeamId           int64  `required:"" name:"team_id"`
	DiscussionNumber int64  `required:"" name:"discussion_number"`
	Content          string `required:"" name:"content" help:"The [reaction type](https://developer.github.com/v3/reactions/#reaction-types) to add to the team discussion."`
}

func (c *ReactionsCreateForTeamDiscussionCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/teams/:team_id/discussions/:discussion_number/reactions"
	c.updatePreview("echo", c.Echo)
	c.updatePreview("squirrel-girl", c.SquirrelGirl)
	c.updateURLPath("team_id", c.TeamId)
	c.updateURLPath("discussion_number", c.DiscussionNumber)
	c.updateBody("content", c.Content)
	return c.doRequest("POST")
}

type ReactionsListForTeamDiscussionCommentCmd struct {
	baseCmd
	Echo             bool   "name:\"echo-preview\" required:\"\" help:\"**Note:** The team discussions API is currently available for developers to preview. See the [blog post](/changes/2018-02-07-team-discussions-api) for full details. To access the API during the preview period, you must provide a custom [media type](/v3/media) in the `Accept` header:\n\n```\napplication/vnd.github.echo-preview+json\n\n```\""
	SquirrelGirl     bool   "name:\"squirrel-girl-preview\" required:\"\" help:\"**Note:** APIs for managing reactions are currently available for developers to preview. See the [blog post](/changes/2016-05-12-reactions-api-preview) for full details. To access the API during the preview period, you must provide a custom [media type](/v3/media) in the `Accept` header:\n\n```\n  application/vnd.github.squirrel-girl-preview+json\n\n```\""
	TeamId           int64  `required:"" name:"team_id"`
	DiscussionNumber int64  `required:"" name:"discussion_number"`
	CommentNumber    int64  `required:"" name:"comment_number"`
	Content          string `name:"content" help:"Returns a single [reaction type](https://developer.github.com/v3/reactions/#reaction-types). Omit this parameter to list all reactions to a team discussion comment."`
	PerPage          int64  `name:"per_page" help:"Results per page (max 100)"`
	Page             int64  `name:"page" help:"Page number of the results to fetch."`
}

func (c *ReactionsListForTeamDiscussionCommentCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/teams/:team_id/discussions/:discussion_number/comments/:comment_number/reactions"
	c.updatePreview("echo", c.Echo)
	c.updatePreview("squirrel-girl", c.SquirrelGirl)
	c.updateURLPath("team_id", c.TeamId)
	c.updateURLPath("discussion_number", c.DiscussionNumber)
	c.updateURLPath("comment_number", c.CommentNumber)
	c.updateURLQuery("content", c.Content)
	c.updateURLQuery("per_page", c.PerPage)
	c.updateURLQuery("page", c.Page)
	return c.doRequest("GET")
}

type ReactionsCreateForTeamDiscussionCommentCmd struct {
	baseCmd
	Echo             bool   "name:\"echo-preview\" required:\"\" help:\"**Note:** The team discussions API is currently available for developers to preview. See the [blog post](/changes/2018-02-07-team-discussions-api) for full details. To access the API during the preview period, you must provide a custom [media type](/v3/media) in the `Accept` header:\n\n```\napplication/vnd.github.echo-preview+json\n\n```\""
	SquirrelGirl     bool   "name:\"squirrel-girl-preview\" required:\"\" help:\"**Note:** APIs for managing reactions are currently available for developers to preview. See the [blog post](/changes/2016-05-12-reactions-api-preview) for full details. To access the API during the preview period, you must provide a custom [media type](/v3/media) in the `Accept` header:\n\n```\n  application/vnd.github.squirrel-girl-preview+json\n\n```\""
	TeamId           int64  `required:"" name:"team_id"`
	DiscussionNumber int64  `required:"" name:"discussion_number"`
	CommentNumber    int64  `required:"" name:"comment_number"`
	Content          string `required:"" name:"content" help:"The [reaction type](https://developer.github.com/v3/reactions/#reaction-types) to add to the team discussion comment."`
}

func (c *ReactionsCreateForTeamDiscussionCommentCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/teams/:team_id/discussions/:discussion_number/comments/:comment_number/reactions"
	c.updatePreview("echo", c.Echo)
	c.updatePreview("squirrel-girl", c.SquirrelGirl)
	c.updateURLPath("team_id", c.TeamId)
	c.updateURLPath("discussion_number", c.DiscussionNumber)
	c.updateURLPath("comment_number", c.CommentNumber)
	c.updateBody("content", c.Content)
	return c.doRequest("POST")
}

type ReactionsDeleteCmd struct {
	baseCmd
	Echo         bool  "name:\"echo-preview\" required:\"\" help:\"**Note:** The team discussions API is currently available for developers to preview. See the [blog post](/changes/2018-02-07-team-discussions-api) for full details. To access the API during the preview period, you must provide a custom [media type](/v3/media) in the `Accept` header:\n\n```\napplication/vnd.github.echo-preview+json\n\n```\""
	SquirrelGirl bool  "name:\"squirrel-girl-preview\" required:\"\" help:\"**Note:** APIs for managing reactions are currently available for developers to preview. See the [blog post](/changes/2016-05-12-reactions-api-preview) for full details. To access the API during the preview period, you must provide a custom [media type](/v3/media) in the `Accept` header:\n\n```\n  application/vnd.github.squirrel-girl-preview+json\n\n```\""
	ReactionId   int64 `required:"" name:"reaction_id"`
}

func (c *ReactionsDeleteCmd) Run(isValueSetMap map[string]bool) error {
	c.isValueSetMap = isValueSetMap
	c.url.Path = "/reactions/:reaction_id"
	c.updatePreview("echo", c.Echo)
	c.updatePreview("squirrel-girl", c.SquirrelGirl)
	c.updateURLPath("reaction_id", c.ReactionId)
	return c.doRequest("DELETE")
}
